exclude: '.git'
default_stages: [commit]
fail_fast: true

repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.29.0
      hooks:
          - id: commitizen
            stages: [commit-msg]