sonar.projectKey=JuanARojasA_dataflat
sonar.organization=jrojas

sonar.projectName=dataflat
sonar.projectVersion=2.0
sonar.test=tests
sonar.python.coverage.reportPaths=coverage-report/coverage.xml
sonar.coverage.exclusions=tests/**