name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev
      - feature/improvements

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
      working-directory: dataflat

    - name: Run tests with coverage
      run: |
        coverage run -m unittest
        coverage xml -o .qodana/code-coverage/coverage.xml
      working-directory: dataflat

    - name: Archive coverage data
      uses: actions/upload-artifact@v2
      with:
        name: py-coverage-data
        path: dataflat/.qodana/code-coverage

    - name: Qodana Scan
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_API_TOKEN }}
      with:
        args: "-i,dataflat,--linter,jetbrains/qodana-python:2024.1"
        pr-mode: false